language: csharp
mono: none
dotnet: 2.2

script:
 - pwsh ./build.ps1

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      # Ref: https://docs.travis-ci.com/user/reference/osx
      dotnet: 2.2.103 # For OSX, we need absolute dotnet version until https://github.com/dotnet/core-setup/issues/4187 is resolved
      before_install:
        - brew update
        - brew tap caskroom/cask
        - brew cask install powershell
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main
              key_url: https://packages.microsoft.com/keys/microsoft.asc
          packages:
            - powershell
