version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test: off
build_script:
- ps: ./build.ps1
artifacts:
- path: artifacts/Kmd.Logic.Audit.Client*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: ZHHP6iRTV5jYf/5K8TGTLPcsjIizChJz2zZnx6JakCUSixeHAoLZC0ho5RT0pHnp
  skip_symbols: true
  on:
    branch: /^(master)$/
- provider: GitHub
  auth_token:
    secure: Gps7M2I9nmkgcYcaOKzYz8CpBNZrrtKDxYq88d9hZqx49oxeqasVEzkvXTnplaQD
  artifact: /Kmd.Logic.Audit.Client.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
